name: {{ cookiecutter.folder_name }}
channels:
  - conda-forge
dependencies:
  # required for mlops framework
  - python >3.10,<3.13
  - mlflow
  - psycopg2-binary
  - asyncpg
  - boto3
  - airflow
  - apache-airflow-providers-cncf-kubernetes
  - apache-airflow-providers-fab
  - jupyter
  - python-dotenv
  - git
  - fsspec
  - typer
  {% if cookiecutter.show_examples == "yes" %}
  # This is only needed for the examples. If you don't need this, please feel free to remove it.
  - keras
  - tensorflow
  - numpy =2.0.2
  {% endif %}
  # Testing
  - pytest-cov
  - pytest
  # Linting
  - ruff
  - isort
  # add your libraries here
